services:
  - name: plato-api
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && gunicorn plato_api.wsgi:application --bind 0.0.0.0:8000