# Generated by Django 5.2.2 on 2025-08-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='depression_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='protocol_selected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentcheckinanswer',
            name='checkin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text Input'), ('radio', 'Radio Button'), ('select', 'Dropdown Select'), ('checkbox', 'Checkbox'), ('textarea', 'Textarea'), ('radio-1', 'Radio-1')], default='text', max_length=20),
        ),
    ]
