# Generated by Django 5.2.2 on 2025-08-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_analysis_assessment_depression_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
