# Generated by Django 5.2.2 on 2025-07-20 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_questionoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option', to='assessments.questionoption'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text Input'), ('radio', 'Radio Button'), ('select', 'Dropdown Select'), ('checkbox', 'Checkbox')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessmentanswer',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
