# Generated by Django 5.2.2 on 2025-08-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_question_is_active_questionoption_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='norm_study_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='norm_study_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
