# Generated by Django 5.2.2 on 2025-08-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_protocol_norm_study_code_protocol_norm_study_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestedprotocol',
            name='first_protocol',
        ),
        migrations.RemoveField(
            model_name='suggestedprotocol',
            name='second_protocol',
        ),
        migrations.RemoveField(
            model_name='suggestedprotocol',
            name='third_protocol',
        ),
        migrations.AddField(
            model_name='suggestedprotocol',
            name='first_norm_study',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suggestedprotocol',
            name='second_norm_study',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suggestedprotocol',
            name='third_norm_study',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
