# Generated by Django 5.2.2 on 2025-08-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_remove_suggestedprotocol_first_protocol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='tdcs_session_per_week',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='tdcs_total_session',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='tdcs_weeks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
