# Generated by Django 5.2.2 on 2025-09-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_protocol_tdcs_session_per_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='short_depression_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
