# Generated by Django 5.2.2 on 2025-08-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('read_time', models.IntegerField()),
                ('published_data', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('is_popular', models.BooleanField()),
                ('cover_image', models.CharField()),
                ('author_avatar', models.CharField()),
            ],
        ),
    ]
