# Generated by Django 5.2.2 on 2025-07-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_staff', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('dob', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_code_expires', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
