# Generated by Django 5.2.2 on 2025-09-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_consent_health_data',
            field=models.BooleanField(default=False),
        ),
    ]
