# Generated by Django 5.2.2 on 2025-09-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_consent_health_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_consent_health_data',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
