# Generated by Django 5.2.2 on 2025-07-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_dob_user_sex_user_verification_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_token_expires',
            new_name='verification_code_expires',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
