# Generated by Django 5.2.2 on 2025-08-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
