# Generated by Django 5.2.2 on 2025-09-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_is_readed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='assessment_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(choices=[('OUTDATED', 'Outdated assessment'), ('COMPLETE', 'Treatment completed')]),
        ),
    ]
