# Generated by Django 5.2.2 on 2025-09-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_assessment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('OUTDATED', 'Outdated assessment'), ('COMPLETE', 'Treatment completed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='assessment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
