# Generated by Django 5.2.2 on 2025-09-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_type_alter_notification_assessment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('OUTDATED', 'Outdated assessment'), ('COMPLETE', 'Treatment completed'), ('OTHERS', 'Others')], default='OTHERS', max_length=50),
        ),
    ]
